using Kontur.GameStats.Models.Entities;

namespace Kontur.GameStats.Models.Json
{
	public class PopularServerJsonModel
	{
		public PopularServerJsonModel()
		{
		}

		public PopularServerJsonModel(ServerEntityModel entity)
		{
			Server = entity.Server;
			Endpoint = entity.Endpoint;
			AverageMatchesPerDay = entity.AvgMatchesPerDay;
		}

		public string Endpoint { get; set; }
		public string Server { get; set; }
		public double AverageMatchesPerDay { get; set; }

		#region autogenerated equality members

		protected bool Equals(PopularServerJsonModel other)
		{
			return string.Equals(Endpoint, other.Endpoint);
		}

		public override bool Equals(object obj)
		{
			if (ReferenceEquals(null, obj)) return false;
			if (ReferenceEquals(this, obj)) return true;
			if (obj.GetType() != this.GetType()) return false;
			return Equals((PopularServerJsonModel) obj);
		}

		public override int GetHashCode()
		{
			return (Endpoint != null ? Endpoint.GetHashCode() : 0);
		}

		#endregion
	}
}