namespace Kontur.GameStats.Models.Json
{
	public class Record
	{
		public string Player { get; set; }
		public int Frags { get; set; }
		public int Kills { get; set; }
		public int Deaths { get; set; }

		public Record()
		{
		}

		#region autogenerated equality members

		protected bool Equals(Record other)
		{
			return string.Equals(Player, other.Player);
		}

		public override bool Equals(object obj)
		{
			if (ReferenceEquals(null, obj)) return false;
			if (ReferenceEquals(this, obj)) return true;
			if (obj.GetType() != this.GetType()) return false;
			return Equals((Record) obj);
		}

		public override int GetHashCode()
		{
			return (Player != null ? Player.GetHashCode() : 0);
		}

		#endregion
	}
}