//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontur.GameStats.Properties {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kontur.GameStats.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advertising error - endpoint of incoming match is not advertised.
        /// </summary>
        internal static string AdvertisingErrorMsg {
            get {
                return ResourceManager.GetString("AdvertisingErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collision - incoming match is already present within database.
        /// </summary>
        internal static string MatchesCollisionMsg {
            get {
                return ResourceManager.GetString("MatchesCollisionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requested all server infos, but no any server info present within database.
        /// </summary>
        internal static string MissingAnyServerinfo {
            get {
                return ResourceManager.GetString("MissingAnyServerinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requested match is not present within database.
        /// </summary>
        internal static string MissingMatchMsg {
            get {
                return ResourceManager.GetString("MissingMatchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requested player is not present within database.
        /// </summary>
        internal static string MissingPlayerMsg {
            get {
                return ResourceManager.GetString("MissingPlayerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requested server info is not present within database.
        /// </summary>
        internal static string MissingServerinfo {
            get {
                return ResourceManager.GetString("MissingServerinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requested stats info references endpoint which is not present within database.
        /// </summary>
        internal static string MissingServerstats {
            get {
                return ResourceManager.GetString("MissingServerstats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collision - found several records with equal player names while building scoreboard.
        /// </summary>
        internal static string ScoreboardCollisionMsg {
            get {
                return ResourceManager.GetString("ScoreboardCollisionMsg", resourceCulture);
            }
        }
    }
}
